package cn.hnist.sharo.mcinema.db.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class CommentBase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_base.comment_id
     *
     * @mbg.generated
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_base.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_base.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_base.upvote
     *
     * @mbg.generated
     */
    private Integer upvote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_base.downvote
     *
     * @mbg.generated
     */
    private Integer downvote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_base.condition_id
     *
     * @mbg.generated
     */
    private Long conditionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_base.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_base.parent_id
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_base.star
     *
     * @mbg.generated
     */
    private BigDecimal star;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_base.condition
     *
     * @mbg.generated
     */
    private Short condition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment_base
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_base.comment_id
     *
     * @return the value of comment_base.comment_id
     *
     * @mbg.generated
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_base.comment_id
     *
     * @param commentId the value for comment_base.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_base.create_time
     *
     * @return the value of comment_base.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_base.create_time
     *
     * @param createTime the value for comment_base.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_base.user_id
     *
     * @return the value of comment_base.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_base.user_id
     *
     * @param userId the value for comment_base.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_base.upvote
     *
     * @return the value of comment_base.upvote
     *
     * @mbg.generated
     */
    public Integer getUpvote() {
        return upvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_base.upvote
     *
     * @param upvote the value for comment_base.upvote
     *
     * @mbg.generated
     */
    public void setUpvote(Integer upvote) {
        this.upvote = upvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_base.downvote
     *
     * @return the value of comment_base.downvote
     *
     * @mbg.generated
     */
    public Integer getDownvote() {
        return downvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_base.downvote
     *
     * @param downvote the value for comment_base.downvote
     *
     * @mbg.generated
     */
    public void setDownvote(Integer downvote) {
        this.downvote = downvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_base.condition_id
     *
     * @return the value of comment_base.condition_id
     *
     * @mbg.generated
     */
    public Long getConditionId() {
        return conditionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_base.condition_id
     *
     * @param conditionId the value for comment_base.condition_id
     *
     * @mbg.generated
     */
    public void setConditionId(Long conditionId) {
        this.conditionId = conditionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_base.content
     *
     * @return the value of comment_base.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_base.content
     *
     * @param content the value for comment_base.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_base.parent_id
     *
     * @return the value of comment_base.parent_id
     *
     * @mbg.generated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_base.parent_id
     *
     * @param parentId the value for comment_base.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_base.star
     *
     * @return the value of comment_base.star
     *
     * @mbg.generated
     */
    public BigDecimal getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_base.star
     *
     * @param star the value for comment_base.star
     *
     * @mbg.generated
     */
    public void setStar(BigDecimal star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_base.condition
     *
     * @return the value of comment_base.condition
     *
     * @mbg.generated
     */
    public Short getCondition() {
        return condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_base.condition
     *
     * @param condition the value for comment_base.condition
     *
     * @mbg.generated
     */
    public void setCondition(Short condition) {
        this.condition = condition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_base
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentId=").append(commentId);
        sb.append(", createTime=").append(createTime);
        sb.append(", userId=").append(userId);
        sb.append(", upvote=").append(upvote);
        sb.append(", downvote=").append(downvote);
        sb.append(", conditionId=").append(conditionId);
        sb.append(", content=").append(content);
        sb.append(", parentId=").append(parentId);
        sb.append(", star=").append(star);
        sb.append(", condition=").append(condition);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_base
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CommentBase other = (CommentBase) that;
        return (this.getCommentId() == null ? other.getCommentId() == null : this.getCommentId().equals(other.getCommentId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUpvote() == null ? other.getUpvote() == null : this.getUpvote().equals(other.getUpvote()))
            && (this.getDownvote() == null ? other.getDownvote() == null : this.getDownvote().equals(other.getDownvote()))
            && (this.getConditionId() == null ? other.getConditionId() == null : this.getConditionId().equals(other.getConditionId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getStar() == null ? other.getStar() == null : this.getStar().equals(other.getStar()))
            && (this.getCondition() == null ? other.getCondition() == null : this.getCondition().equals(other.getCondition()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_base
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCommentId() == null) ? 0 : getCommentId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUpvote() == null) ? 0 : getUpvote().hashCode());
        result = prime * result + ((getDownvote() == null) ? 0 : getDownvote().hashCode());
        result = prime * result + ((getConditionId() == null) ? 0 : getConditionId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getStar() == null) ? 0 : getStar().hashCode());
        result = prime * result + ((getCondition() == null) ? 0 : getCondition().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table comment_base
     *
     * @mbg.generated
     */
    public enum Column {
        commentId("comment_id", "commentId", "BIGINT", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        userId("user_id", "userId", "BIGINT", false),
        upvote("upvote", "upvote", "INTEGER", false),
        downvote("downvote", "downvote", "INTEGER", false),
        conditionId("condition_id", "conditionId", "BIGINT", false),
        content("content", "content", "VARCHAR", false),
        parentId("parent_id", "parentId", "BIGINT", false),
        star("star", "star", "DECIMAL", false),
        condition("condition", "condition", "SMALLINT", true);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table comment_base
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}