package cn.hnist.sharo.mcinema.db.dao;

import cn.hnist.sharo.mcinema.db.pojo.CommentVote;
import cn.hnist.sharo.mcinema.db.pojo.CommentVoteExample;
import cn.hnist.sharo.mcinema.db.pojo.CommentVoteKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentVoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    long countByExample(CommentVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    int deleteByExample(CommentVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(CommentVoteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    int insert(CommentVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    int insertSelective(CommentVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    CommentVote selectOneByExample(CommentVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    CommentVote selectOneByExampleSelective(@Param("example") CommentVoteExample example, @Param("selective") CommentVote.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    List<CommentVote> selectByExampleSelective(@Param("example") CommentVoteExample example, @Param("selective") CommentVote.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    List<CommentVote> selectByExample(CommentVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    CommentVote selectByPrimaryKeySelective(@Param("record") CommentVoteKey key, @Param("selective") CommentVote.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    CommentVote selectByPrimaryKey(CommentVoteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CommentVote record, @Param("example") CommentVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CommentVote record, @Param("example") CommentVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommentVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_vote
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommentVote record);
}