package cn.hnist.sharo.mcinema.db.dao;

import cn.hnist.sharo.mcinema.db.pojo.FilmBase;
import cn.hnist.sharo.mcinema.db.pojo.FilmBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilmBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    long countByExample(FilmBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    int deleteByExample(FilmBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long filmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    int insert(FilmBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    int insertSelective(FilmBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    FilmBase selectOneByExample(FilmBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    FilmBase selectOneByExampleSelective(@Param("example") FilmBaseExample example, @Param("selective") FilmBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    List<FilmBase> selectByExampleSelective(@Param("example") FilmBaseExample example, @Param("selective") FilmBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    List<FilmBase> selectByExample(FilmBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    FilmBase selectByPrimaryKeySelective(@Param("filmId") Long filmId, @Param("selective") FilmBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    FilmBase selectByPrimaryKey(Long filmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    FilmBase selectByPrimaryKeyWithLogicalDelete(@Param("filmId") Long filmId, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FilmBase record, @Param("example") FilmBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FilmBase record, @Param("example") FilmBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FilmBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FilmBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") FilmBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_base
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Long filmId);
}