package cn.hnist.sharo.mcinema.db.dao;

import cn.hnist.sharo.mcinema.db.pojo.SceneType;
import cn.hnist.sharo.mcinema.db.pojo.SceneTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SceneTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    long countByExample(SceneTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    int deleteByExample(SceneTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sceneTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    int insert(SceneType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    int insertSelective(SceneType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    SceneType selectOneByExample(SceneTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    SceneType selectOneByExampleSelective(@Param("example") SceneTypeExample example, @Param("selective") SceneType.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    List<SceneType> selectByExampleSelective(@Param("example") SceneTypeExample example, @Param("selective") SceneType.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    List<SceneType> selectByExample(SceneTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    SceneType selectByPrimaryKeySelective(@Param("sceneTypeId") Integer sceneTypeId, @Param("selective") SceneType.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    SceneType selectByPrimaryKey(Integer sceneTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SceneType record, @Param("example") SceneTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SceneType record, @Param("example") SceneTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SceneType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scene_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SceneType record);
}