package cn.hnist.sharo.mcinema.db.dao;

import cn.hnist.sharo.mcinema.db.pojo.SystemConstant;
import cn.hnist.sharo.mcinema.db.pojo.SystemConstantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemConstantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    long countByExample(SystemConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    int deleteByExample(SystemConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer constantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    int insert(SystemConstant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    int insertSelective(SystemConstant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    SystemConstant selectOneByExample(SystemConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    SystemConstant selectOneByExampleSelective(@Param("example") SystemConstantExample example, @Param("selective") SystemConstant.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    List<SystemConstant> selectByExampleSelective(@Param("example") SystemConstantExample example, @Param("selective") SystemConstant.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    List<SystemConstant> selectByExample(SystemConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    SystemConstant selectByPrimaryKeySelective(@Param("constantId") Integer constantId, @Param("selective") SystemConstant.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    SystemConstant selectByPrimaryKey(Integer constantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    SystemConstant selectByPrimaryKeyWithLogicalDelete(@Param("constantId") Integer constantId, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SystemConstant record, @Param("example") SystemConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SystemConstant record, @Param("example") SystemConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemConstant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemConstant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SystemConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_constant
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer constantId);
}